// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/dicionario.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fdicionario_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fdicionario_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fdicionario_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fdicionario_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_proto_2fdicionario_2eproto;
namespace dicionario {
class PrintaRequest;
struct PrintaRequestDefaultTypeInternal;
extern PrintaRequestDefaultTypeInternal _PrintaRequest_default_instance_;
class PrintaResposta;
struct PrintaRespostaDefaultTypeInternal;
extern PrintaRespostaDefaultTypeInternal _PrintaResposta_default_instance_;
class PrintaResposta_DicionarioEntry_DoNotUse;
struct PrintaResposta_DicionarioEntry_DoNotUseDefaultTypeInternal;
extern PrintaResposta_DicionarioEntry_DoNotUseDefaultTypeInternal _PrintaResposta_DicionarioEntry_DoNotUse_default_instance_;
class RequestPalavra;
struct RequestPalavraDefaultTypeInternal;
extern RequestPalavraDefaultTypeInternal _RequestPalavra_default_instance_;
class RespostaPalavra;
struct RespostaPalavraDefaultTypeInternal;
extern RespostaPalavraDefaultTypeInternal _RespostaPalavra_default_instance_;
}  // namespace dicionario
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace dicionario {

// ===================================================================


// -------------------------------------------------------------------

class RespostaPalavra final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dicionario.RespostaPalavra) */ {
 public:
  inline RespostaPalavra() : RespostaPalavra(nullptr) {}
  ~RespostaPalavra() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RespostaPalavra(
      ::google::protobuf::internal::ConstantInitialized);

  inline RespostaPalavra(const RespostaPalavra& from) : RespostaPalavra(nullptr, from) {}
  inline RespostaPalavra(RespostaPalavra&& from) noexcept
      : RespostaPalavra(nullptr, std::move(from)) {}
  inline RespostaPalavra& operator=(const RespostaPalavra& from) {
    CopyFrom(from);
    return *this;
  }
  inline RespostaPalavra& operator=(RespostaPalavra&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RespostaPalavra& default_instance() {
    return *internal_default_instance();
  }
  static inline const RespostaPalavra* internal_default_instance() {
    return reinterpret_cast<const RespostaPalavra*>(
        &_RespostaPalavra_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RespostaPalavra& a, RespostaPalavra& b) { a.Swap(&b); }
  inline void Swap(RespostaPalavra* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RespostaPalavra* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RespostaPalavra* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<RespostaPalavra>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RespostaPalavra& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RespostaPalavra& from) { RespostaPalavra::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(RespostaPalavra* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "dicionario.RespostaPalavra"; }

 protected:
  explicit RespostaPalavra(::google::protobuf::Arena* arena);
  RespostaPalavra(::google::protobuf::Arena* arena, const RespostaPalavra& from);
  RespostaPalavra(::google::protobuf::Arena* arena, RespostaPalavra&& from) noexcept
      : RespostaPalavra(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message() ;
  const std::string& message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* value);

  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(
      const std::string& value);
  std::string* _internal_mutable_message();

  public:
  // @@protoc_insertion_point(class_scope:dicionario.RespostaPalavra)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      42, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_RespostaPalavra_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RespostaPalavra& from_msg);
    ::google::protobuf::internal::ArenaStringPtr message_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fdicionario_2eproto;
};
// -------------------------------------------------------------------

class RequestPalavra final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dicionario.RequestPalavra) */ {
 public:
  inline RequestPalavra() : RequestPalavra(nullptr) {}
  ~RequestPalavra() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestPalavra(
      ::google::protobuf::internal::ConstantInitialized);

  inline RequestPalavra(const RequestPalavra& from) : RequestPalavra(nullptr, from) {}
  inline RequestPalavra(RequestPalavra&& from) noexcept
      : RequestPalavra(nullptr, std::move(from)) {}
  inline RequestPalavra& operator=(const RequestPalavra& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestPalavra& operator=(RequestPalavra&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestPalavra& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestPalavra* internal_default_instance() {
    return reinterpret_cast<const RequestPalavra*>(
        &_RequestPalavra_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(RequestPalavra& a, RequestPalavra& b) { a.Swap(&b); }
  inline void Swap(RequestPalavra* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestPalavra* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestPalavra* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<RequestPalavra>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RequestPalavra& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RequestPalavra& from) { RequestPalavra::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(RequestPalavra* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "dicionario.RequestPalavra"; }

 protected:
  explicit RequestPalavra(::google::protobuf::Arena* arena);
  RequestPalavra(::google::protobuf::Arena* arena, const RequestPalavra& from);
  RequestPalavra(::google::protobuf::Arena* arena, RequestPalavra&& from) noexcept
      : RequestPalavra(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWordFieldNumber = 1,
  };
  // string word = 1;
  void clear_word() ;
  const std::string& word() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_word(Arg_&& arg, Args_... args);
  std::string* mutable_word();
  PROTOBUF_NODISCARD std::string* release_word();
  void set_allocated_word(std::string* value);

  private:
  const std::string& _internal_word() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_word(
      const std::string& value);
  std::string* _internal_mutable_word();

  public:
  // @@protoc_insertion_point(class_scope:dicionario.RequestPalavra)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      38, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_RequestPalavra_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const RequestPalavra& from_msg);
    ::google::protobuf::internal::ArenaStringPtr word_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fdicionario_2eproto;
};
// -------------------------------------------------------------------

class PrintaResposta_DicionarioEntry_DoNotUse final
    : public ::google::protobuf::internal::MapEntry<
          PrintaResposta_DicionarioEntry_DoNotUse, std::string, ::int32_t,
          ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
          ::google::protobuf::internal::WireFormatLite::TYPE_INT32> {
 public:
  using SuperType = ::google::protobuf::internal::MapEntry<
      PrintaResposta_DicionarioEntry_DoNotUse, std::string, ::int32_t,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>;
  PrintaResposta_DicionarioEntry_DoNotUse();
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PrintaResposta_DicionarioEntry_DoNotUse(
      ::google::protobuf::internal::ConstantInitialized);
  explicit PrintaResposta_DicionarioEntry_DoNotUse(::google::protobuf::Arena* arena);
  static const PrintaResposta_DicionarioEntry_DoNotUse* internal_default_instance() {
    return reinterpret_cast<const PrintaResposta_DicionarioEntry_DoNotUse*>(
        &_PrintaResposta_DicionarioEntry_DoNotUse_default_instance_);
  }
const ::google::protobuf::Message::ClassData* GetClassData() const final;
  friend struct ::TableStruct_proto_2fdicionario_2eproto;
};
// -------------------------------------------------------------------

class PrintaRequest final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:dicionario.PrintaRequest) */ {
 public:
  inline PrintaRequest() : PrintaRequest(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PrintaRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline PrintaRequest(const PrintaRequest& from) : PrintaRequest(nullptr, from) {}
  inline PrintaRequest(PrintaRequest&& from) noexcept
      : PrintaRequest(nullptr, std::move(from)) {}
  inline PrintaRequest& operator=(const PrintaRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrintaRequest& operator=(PrintaRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrintaRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrintaRequest* internal_default_instance() {
    return reinterpret_cast<const PrintaRequest*>(
        &_PrintaRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PrintaRequest& a, PrintaRequest& b) { a.Swap(&b); }
  inline void Swap(PrintaRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrintaRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrintaRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<PrintaRequest>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const PrintaRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const PrintaRequest& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "dicionario.PrintaRequest"; }

 protected:
  explicit PrintaRequest(::google::protobuf::Arena* arena);
  PrintaRequest(::google::protobuf::Arena* arena, const PrintaRequest& from);
  PrintaRequest(::google::protobuf::Arena* arena, PrintaRequest&& from) noexcept
      : PrintaRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ZeroFieldsBase::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:dicionario.PrintaRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_PrintaRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PrintaRequest& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_proto_2fdicionario_2eproto;
};
// -------------------------------------------------------------------

class PrintaResposta final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:dicionario.PrintaResposta) */ {
 public:
  inline PrintaResposta() : PrintaResposta(nullptr) {}
  ~PrintaResposta() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PrintaResposta(
      ::google::protobuf::internal::ConstantInitialized);

  inline PrintaResposta(const PrintaResposta& from) : PrintaResposta(nullptr, from) {}
  inline PrintaResposta(PrintaResposta&& from) noexcept
      : PrintaResposta(nullptr, std::move(from)) {}
  inline PrintaResposta& operator=(const PrintaResposta& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrintaResposta& operator=(PrintaResposta&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PrintaResposta& default_instance() {
    return *internal_default_instance();
  }
  static inline const PrintaResposta* internal_default_instance() {
    return reinterpret_cast<const PrintaResposta*>(
        &_PrintaResposta_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(PrintaResposta& a, PrintaResposta& b) { a.Swap(&b); }
  inline void Swap(PrintaResposta* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PrintaResposta* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PrintaResposta* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<PrintaResposta>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PrintaResposta& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PrintaResposta& from) { PrintaResposta::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PrintaResposta* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "dicionario.PrintaResposta"; }

 protected:
  explicit PrintaResposta(::google::protobuf::Arena* arena);
  PrintaResposta(::google::protobuf::Arena* arena, const PrintaResposta& from);
  PrintaResposta(::google::protobuf::Arena* arena, PrintaResposta&& from) noexcept
      : PrintaResposta(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kDicionarioFieldNumber = 1,
  };
  // map<string, int32> dicionario = 1;
  int dicionario_size() const;
  private:
  int _internal_dicionario_size() const;

  public:
  void clear_dicionario() ;
  const ::google::protobuf::Map<std::string, ::int32_t>& dicionario() const;
  ::google::protobuf::Map<std::string, ::int32_t>* mutable_dicionario();

  private:
  const ::google::protobuf::Map<std::string, ::int32_t>& _internal_dicionario() const;
  ::google::protobuf::Map<std::string, ::int32_t>* _internal_mutable_dicionario();

  public:
  // @@protoc_insertion_point(class_scope:dicionario.PrintaResposta)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      44, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_PrintaResposta_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PrintaResposta& from_msg);
    ::google::protobuf::internal::MapField<PrintaResposta_DicionarioEntry_DoNotUse, std::string, ::int32_t,
                      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
                      ::google::protobuf::internal::WireFormatLite::TYPE_INT32>
        dicionario_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fdicionario_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// RequestPalavra

// string word = 1;
inline void RequestPalavra::clear_word() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.word_.ClearToEmpty();
}
inline const std::string& RequestPalavra::word() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dicionario.RequestPalavra.word)
  return _internal_word();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RequestPalavra::set_word(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.word_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:dicionario.RequestPalavra.word)
}
inline std::string* RequestPalavra::mutable_word() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_word();
  // @@protoc_insertion_point(field_mutable:dicionario.RequestPalavra.word)
  return _s;
}
inline const std::string& RequestPalavra::_internal_word() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.word_.Get();
}
inline void RequestPalavra::_internal_set_word(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.word_.Set(value, GetArena());
}
inline std::string* RequestPalavra::_internal_mutable_word() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.word_.Mutable( GetArena());
}
inline std::string* RequestPalavra::release_word() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dicionario.RequestPalavra.word)
  return _impl_.word_.Release();
}
inline void RequestPalavra::set_allocated_word(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.word_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.word_.IsDefault()) {
          _impl_.word_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:dicionario.RequestPalavra.word)
}

// -------------------------------------------------------------------

// RespostaPalavra

// string message = 1;
inline void RespostaPalavra::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
}
inline const std::string& RespostaPalavra::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:dicionario.RespostaPalavra.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RespostaPalavra::set_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:dicionario.RespostaPalavra.message)
}
inline std::string* RespostaPalavra::mutable_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:dicionario.RespostaPalavra.message)
  return _s;
}
inline const std::string& RespostaPalavra::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void RespostaPalavra::_internal_set_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline std::string* RespostaPalavra::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline std::string* RespostaPalavra::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:dicionario.RespostaPalavra.message)
  return _impl_.message_.Release();
}
inline void RespostaPalavra::set_allocated_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.message_.IsDefault()) {
          _impl_.message_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:dicionario.RespostaPalavra.message)
}

// -------------------------------------------------------------------

// PrintaRequest

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PrintaResposta

// map<string, int32> dicionario = 1;
inline int PrintaResposta::_internal_dicionario_size() const {
  return _internal_dicionario().size();
}
inline int PrintaResposta::dicionario_size() const {
  return _internal_dicionario_size();
}
inline void PrintaResposta::clear_dicionario() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dicionario_.Clear();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& PrintaResposta::_internal_dicionario() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.dicionario_.GetMap();
}
inline const ::google::protobuf::Map<std::string, ::int32_t>& PrintaResposta::dicionario() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_map:dicionario.PrintaResposta.dicionario)
  return _internal_dicionario();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* PrintaResposta::_internal_mutable_dicionario() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.dicionario_.MutableMap();
}
inline ::google::protobuf::Map<std::string, ::int32_t>* PrintaResposta::mutable_dicionario() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_map:dicionario.PrintaResposta.dicionario)
  return _internal_mutable_dicionario();
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace dicionario


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_proto_2fdicionario_2eproto_2epb_2eh
