// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/dicionario.proto
#ifndef GRPC_proto_2fdicionario_2eproto__INCLUDED
#define GRPC_proto_2fdicionario_2eproto__INCLUDED

#include "proto/dicionario.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace dicionario {

class DicionarioService final {
 public:
  static constexpr char const* service_full_name() {
    return "dicionario.DicionarioService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status AddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::dicionario::RespostaPalavra* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::RespostaPalavra>> AsyncAddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::RespostaPalavra>>(AsyncAddPalavraRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::RespostaPalavra>> PrepareAsyncAddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::RespostaPalavra>>(PrepareAsyncAddPalavraRaw(context, request, cq));
    }
    virtual ::grpc::Status PrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::dicionario::PrintaResposta* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::PrintaResposta>> AsyncPrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::PrintaResposta>>(AsyncPrintaDicionarioRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::PrintaResposta>> PrepareAsyncPrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::PrintaResposta>>(PrepareAsyncPrintaDicionarioRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void AddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra* request, ::dicionario::RespostaPalavra* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra* request, ::dicionario::RespostaPalavra* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void PrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest* request, ::dicionario::PrintaResposta* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest* request, ::dicionario::PrintaResposta* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::RespostaPalavra>* AsyncAddPalavraRaw(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::RespostaPalavra>* PrepareAsyncAddPalavraRaw(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::PrintaResposta>* AsyncPrintaDicionarioRaw(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dicionario::PrintaResposta>* PrepareAsyncPrintaDicionarioRaw(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::dicionario::RespostaPalavra* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dicionario::RespostaPalavra>> AsyncAddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dicionario::RespostaPalavra>>(AsyncAddPalavraRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dicionario::RespostaPalavra>> PrepareAsyncAddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dicionario::RespostaPalavra>>(PrepareAsyncAddPalavraRaw(context, request, cq));
    }
    ::grpc::Status PrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::dicionario::PrintaResposta* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dicionario::PrintaResposta>> AsyncPrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dicionario::PrintaResposta>>(AsyncPrintaDicionarioRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dicionario::PrintaResposta>> PrepareAsyncPrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dicionario::PrintaResposta>>(PrepareAsyncPrintaDicionarioRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra* request, ::dicionario::RespostaPalavra* response, std::function<void(::grpc::Status)>) override;
      void AddPalavra(::grpc::ClientContext* context, const ::dicionario::RequestPalavra* request, ::dicionario::RespostaPalavra* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest* request, ::dicionario::PrintaResposta* response, std::function<void(::grpc::Status)>) override;
      void PrintaDicionario(::grpc::ClientContext* context, const ::dicionario::PrintaRequest* request, ::dicionario::PrintaResposta* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::dicionario::RespostaPalavra>* AsyncAddPalavraRaw(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dicionario::RespostaPalavra>* PrepareAsyncAddPalavraRaw(::grpc::ClientContext* context, const ::dicionario::RequestPalavra& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dicionario::PrintaResposta>* AsyncPrintaDicionarioRaw(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dicionario::PrintaResposta>* PrepareAsyncPrintaDicionarioRaw(::grpc::ClientContext* context, const ::dicionario::PrintaRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AddPalavra_;
    const ::grpc::internal::RpcMethod rpcmethod_PrintaDicionario_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status AddPalavra(::grpc::ServerContext* context, const ::dicionario::RequestPalavra* request, ::dicionario::RespostaPalavra* response);
    virtual ::grpc::Status PrintaDicionario(::grpc::ServerContext* context, const ::dicionario::PrintaRequest* request, ::dicionario::PrintaResposta* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AddPalavra : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddPalavra() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AddPalavra() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPalavra(::grpc::ServerContext* /*context*/, const ::dicionario::RequestPalavra* /*request*/, ::dicionario::RespostaPalavra* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddPalavra(::grpc::ServerContext* context, ::dicionario::RequestPalavra* request, ::grpc::ServerAsyncResponseWriter< ::dicionario::RespostaPalavra>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PrintaDicionario : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PrintaDicionario() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PrintaDicionario() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrintaDicionario(::grpc::ServerContext* /*context*/, const ::dicionario::PrintaRequest* /*request*/, ::dicionario::PrintaResposta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrintaDicionario(::grpc::ServerContext* context, ::dicionario::PrintaRequest* request, ::grpc::ServerAsyncResponseWriter< ::dicionario::PrintaResposta>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AddPalavra<WithAsyncMethod_PrintaDicionario<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AddPalavra : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddPalavra() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::dicionario::RequestPalavra, ::dicionario::RespostaPalavra>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::dicionario::RequestPalavra* request, ::dicionario::RespostaPalavra* response) { return this->AddPalavra(context, request, response); }));}
    void SetMessageAllocatorFor_AddPalavra(
        ::grpc::MessageAllocator< ::dicionario::RequestPalavra, ::dicionario::RespostaPalavra>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::dicionario::RequestPalavra, ::dicionario::RespostaPalavra>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddPalavra() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPalavra(::grpc::ServerContext* /*context*/, const ::dicionario::RequestPalavra* /*request*/, ::dicionario::RespostaPalavra* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddPalavra(
      ::grpc::CallbackServerContext* /*context*/, const ::dicionario::RequestPalavra* /*request*/, ::dicionario::RespostaPalavra* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PrintaDicionario : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PrintaDicionario() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::dicionario::PrintaRequest, ::dicionario::PrintaResposta>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::dicionario::PrintaRequest* request, ::dicionario::PrintaResposta* response) { return this->PrintaDicionario(context, request, response); }));}
    void SetMessageAllocatorFor_PrintaDicionario(
        ::grpc::MessageAllocator< ::dicionario::PrintaRequest, ::dicionario::PrintaResposta>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::dicionario::PrintaRequest, ::dicionario::PrintaResposta>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PrintaDicionario() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrintaDicionario(::grpc::ServerContext* /*context*/, const ::dicionario::PrintaRequest* /*request*/, ::dicionario::PrintaResposta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PrintaDicionario(
      ::grpc::CallbackServerContext* /*context*/, const ::dicionario::PrintaRequest* /*request*/, ::dicionario::PrintaResposta* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AddPalavra<WithCallbackMethod_PrintaDicionario<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AddPalavra : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddPalavra() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AddPalavra() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPalavra(::grpc::ServerContext* /*context*/, const ::dicionario::RequestPalavra* /*request*/, ::dicionario::RespostaPalavra* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PrintaDicionario : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PrintaDicionario() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PrintaDicionario() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrintaDicionario(::grpc::ServerContext* /*context*/, const ::dicionario::PrintaRequest* /*request*/, ::dicionario::PrintaResposta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddPalavra : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddPalavra() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AddPalavra() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPalavra(::grpc::ServerContext* /*context*/, const ::dicionario::RequestPalavra* /*request*/, ::dicionario::RespostaPalavra* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddPalavra(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PrintaDicionario : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PrintaDicionario() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PrintaDicionario() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrintaDicionario(::grpc::ServerContext* /*context*/, const ::dicionario::PrintaRequest* /*request*/, ::dicionario::PrintaResposta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrintaDicionario(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddPalavra : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddPalavra() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddPalavra(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddPalavra() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddPalavra(::grpc::ServerContext* /*context*/, const ::dicionario::RequestPalavra* /*request*/, ::dicionario::RespostaPalavra* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddPalavra(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PrintaDicionario : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PrintaDicionario() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PrintaDicionario(context, request, response); }));
    }
    ~WithRawCallbackMethod_PrintaDicionario() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PrintaDicionario(::grpc::ServerContext* /*context*/, const ::dicionario::PrintaRequest* /*request*/, ::dicionario::PrintaResposta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PrintaDicionario(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddPalavra : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddPalavra() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::dicionario::RequestPalavra, ::dicionario::RespostaPalavra>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::dicionario::RequestPalavra, ::dicionario::RespostaPalavra>* streamer) {
                       return this->StreamedAddPalavra(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddPalavra() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddPalavra(::grpc::ServerContext* /*context*/, const ::dicionario::RequestPalavra* /*request*/, ::dicionario::RespostaPalavra* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddPalavra(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dicionario::RequestPalavra,::dicionario::RespostaPalavra>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PrintaDicionario : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PrintaDicionario() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::dicionario::PrintaRequest, ::dicionario::PrintaResposta>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::dicionario::PrintaRequest, ::dicionario::PrintaResposta>* streamer) {
                       return this->StreamedPrintaDicionario(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PrintaDicionario() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PrintaDicionario(::grpc::ServerContext* /*context*/, const ::dicionario::PrintaRequest* /*request*/, ::dicionario::PrintaResposta* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPrintaDicionario(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dicionario::PrintaRequest,::dicionario::PrintaResposta>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddPalavra<WithStreamedUnaryMethod_PrintaDicionario<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddPalavra<WithStreamedUnaryMethod_PrintaDicionario<Service > > StreamedService;
};

}  // namespace dicionario


#endif  // GRPC_proto_2fdicionario_2eproto__INCLUDED
