// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/dicionario.proto
// Protobuf C++ Version: 5.27.2

#include "proto/dicionario.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace dicionario {

inline constexpr RespostaPalavra::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RespostaPalavra::RespostaPalavra(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RespostaPalavraDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespostaPalavraDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespostaPalavraDefaultTypeInternal() {}
  union {
    RespostaPalavra _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespostaPalavraDefaultTypeInternal _RespostaPalavra_default_instance_;

inline constexpr RequestPalavra::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : word_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestPalavra::RequestPalavra(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RequestPalavraDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestPalavraDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestPalavraDefaultTypeInternal() {}
  union {
    RequestPalavra _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestPalavraDefaultTypeInternal _RequestPalavra_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR PrintaResposta_DicionarioEntry_DoNotUse::PrintaResposta_DicionarioEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct PrintaResposta_DicionarioEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrintaResposta_DicionarioEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrintaResposta_DicionarioEntry_DoNotUseDefaultTypeInternal() {}
  union {
    PrintaResposta_DicionarioEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrintaResposta_DicionarioEntry_DoNotUseDefaultTypeInternal _PrintaResposta_DicionarioEntry_DoNotUse_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR PrintaRequest::PrintaRequest(::_pbi::ConstantInitialized) {}
struct PrintaRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrintaRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrintaRequestDefaultTypeInternal() {}
  union {
    PrintaRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrintaRequestDefaultTypeInternal _PrintaRequest_default_instance_;

inline constexpr PrintaResposta::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dicionario_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PrintaResposta::PrintaResposta(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PrintaRespostaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PrintaRespostaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PrintaRespostaDefaultTypeInternal() {}
  union {
    PrintaResposta _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PrintaRespostaDefaultTypeInternal _PrintaResposta_default_instance_;
}  // namespace dicionario
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_proto_2fdicionario_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_proto_2fdicionario_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fdicionario_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dicionario::RequestPalavra, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dicionario::RequestPalavra, _impl_.word_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dicionario::RespostaPalavra, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dicionario::RespostaPalavra, _impl_.message_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dicionario::PrintaRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dicionario::PrintaResposta_DicionarioEntry_DoNotUse, _has_bits_),
        PROTOBUF_FIELD_OFFSET(::dicionario::PrintaResposta_DicionarioEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dicionario::PrintaResposta_DicionarioEntry_DoNotUse, key_),
        PROTOBUF_FIELD_OFFSET(::dicionario::PrintaResposta_DicionarioEntry_DoNotUse, value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::dicionario::PrintaResposta, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::dicionario::PrintaResposta, _impl_.dicionario_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::dicionario::RequestPalavra)},
        {9, -1, -1, sizeof(::dicionario::RespostaPalavra)},
        {18, -1, -1, sizeof(::dicionario::PrintaRequest)},
        {26, 36, -1, sizeof(::dicionario::PrintaResposta_DicionarioEntry_DoNotUse)},
        {38, -1, -1, sizeof(::dicionario::PrintaResposta)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::dicionario::_RequestPalavra_default_instance_._instance,
    &::dicionario::_RespostaPalavra_default_instance_._instance,
    &::dicionario::_PrintaRequest_default_instance_._instance,
    &::dicionario::_PrintaResposta_DicionarioEntry_DoNotUse_default_instance_._instance,
    &::dicionario::_PrintaResposta_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fdicionario_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026proto/dicionario.proto\022\ndicionario\"\036\n\016"
    "RequestPalavra\022\014\n\004word\030\001 \001(\t\"\"\n\017Resposta"
    "Palavra\022\017\n\007message\030\001 \001(\t\"\017\n\rPrintaReques"
    "t\"\203\001\n\016PrintaResposta\022>\n\ndicionario\030\001 \003(\013"
    "2*.dicionario.PrintaResposta.DicionarioE"
    "ntry\0321\n\017DicionarioEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005"
    "value\030\002 \001(\005:\0028\0012\245\001\n\021DicionarioService\022E\n"
    "\nAddPalavra\022\032.dicionario.RequestPalavra\032"
    "\033.dicionario.RespostaPalavra\022I\n\020PrintaDi"
    "cionario\022\031.dicionario.PrintaRequest\032\032.di"
    "cionario.PrintaRespostab\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2fdicionario_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fdicionario_2eproto = {
    false,
    false,
    431,
    descriptor_table_protodef_proto_2fdicionario_2eproto,
    "proto/dicionario.proto",
    &descriptor_table_proto_2fdicionario_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_proto_2fdicionario_2eproto::offsets,
    file_level_enum_descriptors_proto_2fdicionario_2eproto,
    file_level_service_descriptors_proto_2fdicionario_2eproto,
};
namespace dicionario {
// ===================================================================

class RequestPalavra::_Internal {
 public:
};

RequestPalavra::RequestPalavra(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dicionario.RequestPalavra)
}
inline PROTOBUF_NDEBUG_INLINE RequestPalavra::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dicionario::RequestPalavra& from_msg)
      : word_(arena, from.word_),
        _cached_size_{0} {}

RequestPalavra::RequestPalavra(
    ::google::protobuf::Arena* arena,
    const RequestPalavra& from)
    : ::google::protobuf::Message(arena) {
  RequestPalavra* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:dicionario.RequestPalavra)
}
inline PROTOBUF_NDEBUG_INLINE RequestPalavra::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : word_(arena),
        _cached_size_{0} {}

inline void RequestPalavra::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RequestPalavra::~RequestPalavra() {
  // @@protoc_insertion_point(destructor:dicionario.RequestPalavra)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RequestPalavra::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.word_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RequestPalavra::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RequestPalavra, _impl_._cached_size_),
              false,
          },
          &RequestPalavra::MergeImpl,
          &RequestPalavra::kDescriptorMethods,
          &descriptor_table_proto_2fdicionario_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 38, 2> RequestPalavra::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RequestPalavra_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dicionario::RequestPalavra>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string word = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RequestPalavra, _impl_.word_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string word = 1;
    {PROTOBUF_FIELD_OFFSET(RequestPalavra, _impl_.word_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\4\0\0\0\0\0\0"
    "dicionario.RequestPalavra"
    "word"
  }},
};

PROTOBUF_NOINLINE void RequestPalavra::Clear() {
// @@protoc_insertion_point(message_clear_start:dicionario.RequestPalavra)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.word_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RequestPalavra::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dicionario.RequestPalavra)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string word = 1;
  if (!this->_internal_word().empty()) {
    const std::string& _s = this->_internal_word();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dicionario.RequestPalavra.word");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dicionario.RequestPalavra)
  return target;
}

::size_t RequestPalavra::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dicionario.RequestPalavra)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string word = 1;
  if (!this->_internal_word().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_word());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RequestPalavra::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RequestPalavra*>(&to_msg);
  auto& from = static_cast<const RequestPalavra&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dicionario.RequestPalavra)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_word().empty()) {
    _this->_internal_set_word(from._internal_word());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestPalavra::CopyFrom(const RequestPalavra& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dicionario.RequestPalavra)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RequestPalavra::InternalSwap(RequestPalavra* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.word_, &other->_impl_.word_, arena);
}

::google::protobuf::Metadata RequestPalavra::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RespostaPalavra::_Internal {
 public:
};

RespostaPalavra::RespostaPalavra(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dicionario.RespostaPalavra)
}
inline PROTOBUF_NDEBUG_INLINE RespostaPalavra::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dicionario::RespostaPalavra& from_msg)
      : message_(arena, from.message_),
        _cached_size_{0} {}

RespostaPalavra::RespostaPalavra(
    ::google::protobuf::Arena* arena,
    const RespostaPalavra& from)
    : ::google::protobuf::Message(arena) {
  RespostaPalavra* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:dicionario.RespostaPalavra)
}
inline PROTOBUF_NDEBUG_INLINE RespostaPalavra::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void RespostaPalavra::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RespostaPalavra::~RespostaPalavra() {
  // @@protoc_insertion_point(destructor:dicionario.RespostaPalavra)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RespostaPalavra::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RespostaPalavra::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(RespostaPalavra, _impl_._cached_size_),
              false,
          },
          &RespostaPalavra::MergeImpl,
          &RespostaPalavra::kDescriptorMethods,
          &descriptor_table_proto_2fdicionario_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 42, 2> RespostaPalavra::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RespostaPalavra_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dicionario::RespostaPalavra>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RespostaPalavra, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(RespostaPalavra, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\7\0\0\0\0\0\0"
    "dicionario.RespostaPalavra"
    "message"
  }},
};

PROTOBUF_NOINLINE void RespostaPalavra::Clear() {
// @@protoc_insertion_point(message_clear_start:dicionario.RespostaPalavra)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* RespostaPalavra::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dicionario.RespostaPalavra)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dicionario.RespostaPalavra.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dicionario.RespostaPalavra)
  return target;
}

::size_t RespostaPalavra::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dicionario.RespostaPalavra)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RespostaPalavra::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RespostaPalavra*>(&to_msg);
  auto& from = static_cast<const RespostaPalavra&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dicionario.RespostaPalavra)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RespostaPalavra::CopyFrom(const RespostaPalavra& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dicionario.RespostaPalavra)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RespostaPalavra::InternalSwap(RespostaPalavra* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata RespostaPalavra::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PrintaRequest::_Internal {
 public:
};

PrintaRequest::PrintaRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:dicionario.PrintaRequest)
}
PrintaRequest::PrintaRequest(
    ::google::protobuf::Arena* arena,
    const PrintaRequest& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  PrintaRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:dicionario.PrintaRequest)
}

const ::google::protobuf::MessageLite::ClassData*
PrintaRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PrintaRequest, _impl_._cached_size_),
              false,
          },
          &PrintaRequest::MergeImpl,
          &PrintaRequest::kDescriptorMethods,
          &descriptor_table_proto_2fdicionario_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> PrintaRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PrintaRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dicionario::PrintaRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};









::google::protobuf::Metadata PrintaRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

PrintaResposta_DicionarioEntry_DoNotUse::PrintaResposta_DicionarioEntry_DoNotUse() {}
PrintaResposta_DicionarioEntry_DoNotUse::PrintaResposta_DicionarioEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
const ::google::protobuf::MessageLite::ClassData*
PrintaResposta_DicionarioEntry_DoNotUse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // tc_table
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PrintaResposta_DicionarioEntry_DoNotUse, _cached_size_),
              false,
          },
          &PrintaResposta_DicionarioEntry_DoNotUse::MergeImpl,
          &PrintaResposta_DicionarioEntry_DoNotUse::kDescriptorMethods,
          &descriptor_table_proto_2fdicionario_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
// ===================================================================

class PrintaResposta::_Internal {
 public:
};

PrintaResposta::PrintaResposta(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:dicionario.PrintaResposta)
}
inline PROTOBUF_NDEBUG_INLINE PrintaResposta::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::dicionario::PrintaResposta& from_msg)
      : dicionario_{visibility, arena, from.dicionario_},
        _cached_size_{0} {}

PrintaResposta::PrintaResposta(
    ::google::protobuf::Arena* arena,
    const PrintaResposta& from)
    : ::google::protobuf::Message(arena) {
  PrintaResposta* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:dicionario.PrintaResposta)
}
inline PROTOBUF_NDEBUG_INLINE PrintaResposta::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : dicionario_{visibility, arena},
        _cached_size_{0} {}

inline void PrintaResposta::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PrintaResposta::~PrintaResposta() {
  // @@protoc_insertion_point(destructor:dicionario.PrintaResposta)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PrintaResposta::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PrintaResposta::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(PrintaResposta, _impl_._cached_size_),
              false,
          },
          &PrintaResposta::MergeImpl,
          &PrintaResposta::kDescriptorMethods,
          &descriptor_table_proto_2fdicionario_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 44, 2> PrintaResposta::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_PrintaResposta_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::dicionario::PrintaResposta>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, int32> dicionario = 1;
    {PROTOBUF_FIELD_OFFSET(PrintaResposta, _impl_.dicionario_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(PrintaResposta()._impl_.dicionario_)>(
        1, 0, 0, 9,
        5)},
  }}, {{
    "\31\12\0\0\0\0\0\0"
    "dicionario.PrintaResposta"
    "dicionario"
  }},
};

PROTOBUF_NOINLINE void PrintaResposta::Clear() {
// @@protoc_insertion_point(message_clear_start:dicionario.PrintaResposta)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.dicionario_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* PrintaResposta::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dicionario.PrintaResposta)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<string, int32> dicionario = 1;
  if (!_internal_dicionario().empty()) {
    using MapType = ::google::protobuf::Map<std::string, ::int32_t>;
    using WireHelper = _pbi::MapEntryFuncs<std::string, ::int32_t,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_INT32>;
    const auto& field = _internal_dicionario();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dicionario.PrintaResposta.dicionario");
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "dicionario.PrintaResposta.dicionario");
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dicionario.PrintaResposta)
  return target;
}

::size_t PrintaResposta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dicionario.PrintaResposta)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // map<string, int32> dicionario = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_dicionario_size());
  for (const auto& entry : _internal_dicionario()) {
    total_size += _pbi::MapEntryFuncs<std::string, ::int32_t,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_INT32>::ByteSizeLong(entry.first, entry.second);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PrintaResposta::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PrintaResposta*>(&to_msg);
  auto& from = static_cast<const PrintaResposta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dicionario.PrintaResposta)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.dicionario_.MergeFrom(from._impl_.dicionario_);
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PrintaResposta::CopyFrom(const PrintaResposta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dicionario.PrintaResposta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PrintaResposta::InternalSwap(PrintaResposta* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.dicionario_.InternalSwap(&other->_impl_.dicionario_);
}

::google::protobuf::Metadata PrintaResposta::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace dicionario
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fdicionario_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
